[package]
name = "rs-image-templating"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "image_template"

[dependencies]
toml = { version = "0.7.2", optional = true }

[features]
default = ["toml-parser"]
toml-parser = ["dep:toml"]
